<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Exception;

class DashboardController extends Controller
{
    public function index()
    {
        $announcements    = collect();
        $classes          = collect();
        $recentActivities = collect();
        $totalMembers     = 0;
        $totalClasses     = 0;

        $supabaseUrl = config('services.supabase.url', env('SUPABASE_URL'));
        $supabaseKey = config('services.supabase.anon_key', env('SUPABASE_ANON_KEY'));

        $memberDetails  = null;
        $memberPosition = 'Active Alumni Member';

        if ($supabaseUrl && $supabaseKey) {
            $supabaseUrl = rtrim($supabaseUrl, '/');

            // 1. Fetch Logged-in User Member Profile Details by Email
            if (Auth::check() && Auth::user()->email) {
                try {
                    $userEmail = strtolower(trim(Auth::user()->email));
                    $memberResponse = Http::withoutVerifying()->withHeaders([
                        'apikey'        => $supabaseKey,
                        'Authorization' => 'Bearer ' . $supabaseKey,
                    ])->get("{$supabaseUrl}/rest/v1/members", [
                        'select' => '*',
                        'email'  => 'eq.' . $userEmail,
                        'limit'  => 1,
                    ]);

                    if ($memberResponse->successful() && !empty($memberResponse->json())) {
                        $memberDetails = $memberResponse->json()[0];
                        if (!empty($memberDetails['position'])) {
                            $memberPosition = $memberDetails['position'];
                        } elseif (!empty($memberDetails['cadet_role'])) {
                            $memberPosition = $memberDetails['cadet_role'];
                        }
                    }
                } catch (Exception $e) {
                    Log::warning('Failed to fetch logged-in member details: ' . $e->getMessage());
                }
            }

            // 2. Fetch filtered activity logs generated by database triggers
            try {
                $logsResponse = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                ])->get("{$supabaseUrl}/rest/v1/activity_logs", [
                    'select' => '*',
                    'order'  => 'created_at.desc',
                    'limit'  => 5,
                ]);

                if ($logsResponse->successful()) {
                    $recentActivities = collect($logsResponse->json())->map(function ($log) {
                        return (object) [
                            'id'          => $log['id'],
                            'description' => $log['description'],
                            'type'        => ucfirst($log['entity_type']),
                            'time_ago'    => Carbon::parse($log['created_at'])->diffForHumans(),
                        ];
                    });
                }
            } catch (Exception $e) {
                Log::warning('Failed to fetch activity logs from Supabase: ' . $e->getMessage());
            }

            // 3. Fetch Members Count
            try {
                $membersCountResponse = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                    'Prefer'        => 'count=exact',
                ])->get("{$supabaseUrl}/rest/v1/members", [
                    'select' => 'id',
                    'limit'  => 1,
                ]);

                if ($membersCountResponse->hasHeader('Content-Range')) {
                    $rangeHeader = $membersCountResponse->header('Content-Range');
                    if (str_contains($rangeHeader, '/')) {
                        $totalMembers = (int) explode('/', $rangeHeader)[1];
                    }
                } else {
                    $totalMembers = count($membersCountResponse->json());
                }
            } catch (Exception $e) {
                Log::warning('Failed to fetch total members count from Supabase: ' . $e->getMessage());
                $totalMembers = User::count() ?: 0;
            }

            // 4. Fetch Announcements
            try {
                $response = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                ])->get("{$supabaseUrl}/rest/v1/announcements", [
                    'select'    => '*',
                    'is_active' => 'eq.true',
                    'or'        => '(expires_at.is.null,expires_at.gte.' . now()->toISOString() . ')',
                    'order'     => 'created_at.desc',
                    'limit'     => 5,
                ]);

                if ($response->successful()) {
                    $announcements = collect($response->json())->map(function ($item) {
                        return (object) [
                            'id'         => $item['id'] ?? null,
                            'title'      => $item['title'] ?? '',
                            'content'    => $item['content'] ?? '',
                            'type'       => $item['type'] ?? 'general',
                            'is_active'  => $item['is_active'] ?? true,
                            'expires_at' => isset($item['expires_at']) ? Carbon::parse($item['expires_at']) : null,
                            'created_at' => isset($item['created_at']) ? Carbon::parse($item['created_at']) : now(),
                        ];
                    });
                }
            } catch (Exception $e) {
                $announcements = collect();
            }

            // 5. Fetch Classes List and Live Total Count from Supabase `public.classes`
            try {
                $classResponse = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                    'Prefer'        => 'count=exact',
                ])->get("{$supabaseUrl}/rest/v1/classes", [
                    'select' => 'id, class_name, class_number, batch_year',
                    'order'  => 'class_number.asc',
                ]);

                if ($classResponse->successful()) {
                    $classes = collect($classResponse->json());
                    if ($classResponse->hasHeader('Content-Range')) {
                        $rangeHeader = $classResponse->header('Content-Range');
                        if (str_contains($rangeHeader, '/')) {
                            $totalClasses = (int) explode('/', $rangeHeader)[1];
                        }
                    } else {
                        $totalClasses = $classes->count();
                    }
                }
            } catch (Exception $e) {
                $classes = collect();
                $totalClasses = 0;
            }
        }

        $totalBlogs  = 8;
        $totalPhotos = 45;

        return view('dashboard', compact(
            'totalMembers',
            'totalClasses',
            'totalBlogs',
            'totalPhotos',
            'announcements',
            'classes',
            'recentActivities',
            'memberPosition',
            'memberDetails'
        ));
    }

    public function updateProfile(Request $request)
    {
        $userEmail = strtolower(trim(Auth::user()->email));

        // Validate ONLY the modifiable fields
        $validated = $request->validate([
            'middle_name'    => 'nullable|string|max:100',
            'last_name'      => 'required|string|max:100',
            'suffix'         => 'nullable|string|max:20',
            'nickname'       => 'nullable|string|max:100',
            'gender'         => 'required|string|max:20',
            'birth_date'     => 'nullable|date',
            'civil_status'   => 'required|string|max:50',
            'address'        => 'required|string',
            'city'           => 'nullable|string|max:100',
            'province'       => 'nullable|string|max:100',
            'country'        => 'nullable|string|max:100',
            'contact_number' => 'required|string|max:30',
            'occupation'     => 'required|string|max:255',
            'company'        => 'nullable|string|max:255',
            'business_name'  => 'nullable|string|max:255',
            'facebook_url'   => 'nullable|url|max:500',
            'profile_photo'  => 'nullable|image|mimes:jpeg,png,jpg,webp|max:5120',
        ]);

        $supabaseUrl = config('services.supabase.url', env('SUPABASE_URL'));
        $supabaseKey = config('services.supabase.anon_key', env('SUPABASE_ANON_KEY'));

        if (!$supabaseUrl || !$supabaseKey) {
            return redirect()->back()->withErrors(['update_profile_error' => 'Supabase configuration missing.'])->withInput();
        }

        $supabaseUrl = rtrim($supabaseUrl, '/');
        $profilePhotoUrl = null;

        // Upload Profile Photo if a new file was supplied
        if ($request->hasFile('profile_photo')) {
            try {
                $file      = $request->file('profile_photo');
                $extension = $file->getClientOriginalExtension() ?: 'jpg';
                $fileName  = 'profile_' . time() . '_' . Str::random(8) . '.' . $extension;

                $uploadEndpoint = "{$supabaseUrl}/storage/v1/object/member-photos/{$fileName}";

                $uploadResponse = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                    'Content-Type'  => $file->getMimeType() ?: 'image/jpeg',
                    'x-upsert'      => 'true',
                ])->withBody(
                    file_get_contents($file->getRealPath()), 
                    $file->getMimeType() ?: 'image/jpeg'
                )->post($uploadEndpoint);

                if ($uploadResponse->successful()) {
                    $profilePhotoUrl = "{$supabaseUrl}/storage/v1/object/public/member-photos/{$fileName}";
                } else {
                    Log::error('Profile photo upload failed', [
                        'status' => $uploadResponse->status(),
                        'body'   => $uploadResponse->body(),
                    ]);
                }
            } catch (\Exception $e) {
                return redirect()->back()->withErrors(['update_profile_error' => 'Photo Upload Failed: ' . $e->getMessage()])->withInput();
            }
        }

        // Payload excludes class_id, cadet_role, email, and first_name
        $payload = [
            'middle_name'    => !empty($validated['middle_name']) ? $validated['middle_name'] : null,
            'last_name'      => $validated['last_name'],
            'suffix'         => !empty($validated['suffix']) ? $validated['suffix'] : null,
            'nickname'       => !empty($validated['nickname']) ? $validated['nickname'] : null,
            'gender'         => $validated['gender'],
            'birth_date'     => !empty($validated['birth_date']) ? $validated['birth_date'] : null,
            'civil_status'   => $validated['civil_status'],
            'address'        => $validated['address'],
            'city'           => !empty($validated['city']) ? $validated['city'] : null,
            'province'       => !empty($validated['province']) ? $validated['province'] : null,
            'country'        => !empty($validated['country']) ? $validated['country'] : 'Philippines',
            'contact_number' => $validated['contact_number'],
            'occupation'     => $validated['occupation'],
            'company'        => !empty($validated['company']) ? $validated['company'] : null,
            'business_name'  => !empty($validated['business_name']) ? $validated['business_name'] : null,
            'facebook_url'   => !empty($validated['facebook_url']) ? $validated['facebook_url'] : null,
            'updated_at'     => now()->toISOString(),
        ];

        if ($profilePhotoUrl) {
            $payload['profile_photo'] = $profilePhotoUrl;
        }

        try {
            $response = Http::withoutVerifying()->withHeaders([
                'apikey'        => $supabaseKey,
                'Authorization' => 'Bearer ' . $supabaseKey,
                'Content-Type'  => 'application/json',
                'Prefer'        => 'return=minimal',
            ])->patch("{$supabaseUrl}/rest/v1/members?email=eq.{$userEmail}", $payload);

            if ($response->successful()) {
                return redirect()->back()->with('success', 'Your profile information has been updated.');
            }

            $errorBody = $response->json();
            return redirect()->back()->withErrors([
                'update_profile_error' => 'Supabase Error: ' . ($errorBody['message'] ?? $response->body())
            ])->withInput();

        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['update_profile_error' => 'Connection Error: ' . $e->getMessage()])->withInput();
        }
    }
    public function storeAnnouncement(Request $request)
    {
        $validated = $request->validate([
            'title'      => 'required|string|max:255',
            'type'       => 'required|string|in:general,urgent',
            'content'    => 'required|string',
            'expires_at' => 'nullable|date',
        ]);

        $supabaseUrl = config('services.supabase.url', env('SUPABASE_URL'));
        $supabaseKey = config('services.supabase.anon_key', env('SUPABASE_ANON_KEY'));

        if ($supabaseUrl && $supabaseKey) {
            $payload = [
                'title'     => $validated['title'],
                'type'      => $validated['type'],
                'content'   => $validated['content'],
                'is_active' => true,
                'expires_at'=> !empty($validated['expires_at']) ? Carbon::parse($validated['expires_at'])->toIso8601String() : null,
            ];

            $response = Http::withHeaders([
                'apikey'        => $supabaseKey,
                'Authorization' => 'Bearer ' . $supabaseKey,
                'Content-Type'  => 'application/json',
                'Prefer'        => 'return=minimal',
            ])->post("{$supabaseUrl}/rest/v1/announcements", $payload);

            if ($response->successful()) {
                return redirect()->back()->with('success', 'Announcement published successfully.');
            }
        }

        return redirect()->back()->withErrors(['error' => 'Failed to publish announcement.']);
    }

    public function storeMember(Request $request)
    {
        $validated = $request->validate([
            'class_id'       => 'nullable|string',
            'cadet_role'     => 'required|string|max:100',
            'first_name'     => 'required|string|max:100',
            'middle_name'    => 'nullable|string|max:100',
            'last_name'      => 'required|string|max:100',
            'suffix'         => 'nullable|string|max:20',
            'nickname'       => 'nullable|string|max:100',
            'gender'         => 'required|string|max:20',
            'birth_date'     => 'nullable|date',
            'civil_status'   => 'required|string|max:50',
            'address'        => 'required|string',
            'city'           => 'nullable|string|max:100',
            'province'       => 'nullable|string|max:100',
            'country'        => 'nullable|string|max:100',
            'contact_number' => 'required|string|max:30',
            'email'          => 'required|email|max:255',
            'occupation'     => 'required|string|max:255',
            'company'        => 'nullable|string|max:255',
            'business_name'  => 'nullable|string|max:255',
            'facebook_url'   => 'nullable|url|max:500',
            'profile_photo'  => 'nullable|image|mimes:jpeg,png,jpg,webp|max:5120',
        ]);

        $supabaseUrl = config('services.supabase.url', env('SUPABASE_URL'));
        $supabaseKey = config('services.supabase.anon_key', env('SUPABASE_ANON_KEY'));

        if (!$supabaseUrl || !$supabaseKey) {
            return redirect()->back()->withErrors(['member_error' => 'Supabase configuration missing.'])->withInput();
        }

        $supabaseUrl = rtrim($supabaseUrl, '/');
        $profilePhotoUrl = null;

        // 1. Upload Profile Photo to Supabase Storage ("member-photos" bucket)
        if ($request->hasFile('profile_photo')) {
            try {
                $file      = $request->file('profile_photo');
                $extension = $file->getClientOriginalExtension() ?: 'jpg';
                $fileName  = 'profile_' . time() . '_' . Str::random(8) . '.' . $extension;

                $uploadEndpoint = "{$supabaseUrl}/storage/v1/object/barons-images/{$fileName}";

                $uploadResponse = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                    'Content-Type'  => $file->getMimeType() ?: 'image/jpeg',
                    'x-upsert'      => 'true',
                ])->withBody(
                    file_get_contents($file->getRealPath()), 
                    $file->getMimeType() ?: 'image/jpeg'
                )->post($uploadEndpoint);

                if ($uploadResponse->successful()) {
                    $profilePhotoUrl = "{$supabaseUrl}/storage/v1/object/public/barons-images/{$fileName}";
                } else {
                    Log::error('Member profile photo upload failed', [
                        'status' => $uploadResponse->status(),
                        'body'   => $uploadResponse->body(),
                    ]);
                }
            } catch (\Exception $e) {
                return redirect()->back()->withErrors(['member_error' => 'Photo Upload Failed: ' . $e->getMessage()])->withInput();
            }
        }

        // 2. Prepare payload matching public.members database table columns
        $payload = [
            'class_id'       => !empty($validated['class_id']) ? $validated['class_id'] : null,
            'cadet_role'     => $validated['cadet_role'] ?? 'Members',
            'first_name'     => $validated['first_name'],
            'middle_name'    => !empty($validated['middle_name']) ? $validated['middle_name'] : null,
            'last_name'      => $validated['last_name'],
            'suffix'         => !empty($validated['suffix']) ? $validated['suffix'] : null,
            'nickname'       => !empty($validated['nickname']) ? $validated['nickname'] : null,
            'gender'         => $validated['gender'],
            'birth_date'     => !empty($validated['birth_date']) ? $validated['birth_date'] : null,
            'civil_status'   => $validated['civil_status'],
            'address'        => $validated['address'],
            'city'           => !empty($validated['city']) ? $validated['city'] : null,
            'province'       => !empty($validated['province']) ? $validated['province'] : null,
            'country'        => !empty($validated['country']) ? $validated['country'] : 'Philippines',
            'contact_number' => $validated['contact_number'],
            'email'          => strtolower($validated['email']),
            'occupation'     => $validated['occupation'],
            'company'        => !empty($validated['company']) ? $validated['company'] : null,
            'business_name'  => !empty($validated['business_name']) ? $validated['business_name'] : null,
            'facebook_url'   => !empty($validated['facebook_url']) ? $validated['facebook_url'] : null,
            'is_public'      => true,
        ];

        if ($profilePhotoUrl) {
            $payload['profile_photo'] = $profilePhotoUrl;
        }

        try {
            // Upsert (INSERT or UPDATE if email exists)
            $response = Http::withoutVerifying()->withHeaders([
                'apikey'        => $supabaseKey,
                'Authorization' => 'Bearer ' . $supabaseKey,
                'Content-Type'  => 'application/json',
                'Prefer'        => 'return=minimal',
            ])->post("{$supabaseUrl}/rest/v1/members", $payload);

            if ($response->successful()) {
                return redirect()->back()->with('success', 'Member details saved successfully.');
            }

            $errorBody = $response->json();
            return redirect()->back()->withErrors([
                'member_error' => 'Supabase Error: ' . ($errorBody['message'] ?? $response->body())
            ])->withInput();

        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['member_error' => 'Connection Error: ' . $e->getMessage()])->withInput();
        }
    }

    public function storeClass(Request $request)
    {
        $validated = $request->validate([
            'class_name'      => 'required|string|max:50',
            'class_number'    => 'nullable|integer|min:1',
            'batch_year'      => 'nullable|integer',
            'corps_commander' => 'nullable|string|max:255',
            'description'     => 'nullable|string',
            'class_logo'      => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048',
        ]);

        $supabaseUrl = config('services.supabase.url', env('SUPABASE_URL'));
        $supabaseKey = config('services.supabase.anon_key', env('SUPABASE_ANON_KEY'));

        if (!$supabaseUrl || !$supabaseKey) {
            return redirect()->back()->withErrors(['class_error' => 'Supabase URL or API Key is missing.']);
        }

        $supabaseUrl = rtrim($supabaseUrl, '/');
        $classLogoUrl = null;

        if ($request->hasFile('class_logo')) {
            try {
                $file      = $request->file('class_logo');
                $extension = $file->getClientOriginalExtension();
                $fileName  = 'classes/logo_' . time() . '_' . Str::random(8) . '.' . $extension;

                $uploadEndpoint = "{$supabaseUrl}/storage/v1/object/barons-images/{$fileName}";

                $uploadResponse = Http::withoutVerifying()->withHeaders([
                    'apikey'        => $supabaseKey,
                    'Authorization' => 'Bearer ' . $supabaseKey,
                    'Content-Type'  => $file->getMimeType(),
                    'x-upsert'      => 'true',
                ])->withBody(
                    file_get_contents($file->getRealPath()),
                    $file->getMimeType()
                )->post($uploadEndpoint);

                if ($uploadResponse->successful()) {
                    $classLogoUrl = "{$supabaseUrl}/storage/v1/object/public/barons-images/{$fileName}";
                } else {
                    $errorMsg = $uploadResponse->json()['message'] ?? $uploadResponse->body();
                    return redirect()->back()->withErrors(['class_error' => 'Logo Upload Failed: ' . $errorMsg]);
                }
            } catch (\Exception $e) {
                return redirect()->back()->withErrors(['class_error' => 'Logo Upload Exception: ' . $e->getMessage()]);
            }
        }

        $payload = [
            'class_name'      => $validated['class_name'],
            'class_number'    => !empty($validated['class_number']) ? (int) $validated['class_number'] : null,
            'batch_year'      => !empty($validated['batch_year']) ? (int) $validated['batch_year'] : null,
            'corps_commander' => !empty($validated['corps_commander']) ? $validated['corps_commander'] : null,
            'description'     => !empty($validated['description']) ? $validated['description'] : null,
            'class_logo'      => $classLogoUrl,
        ];

        try {
            $response = Http::withoutVerifying()->withHeaders([
                'apikey'        => $supabaseKey,
                'Authorization' => 'Bearer ' . $supabaseKey,
                'Content-Type'  => 'application/json',
                'Prefer'        => 'return=minimal',
            ])->post("{$supabaseUrl}/rest/v1/classes", $payload);

            if ($response->successful()) {
                return redirect()->back()->with('success', 'New class created successfully.');
            }

            $errorBody = $response->json();
            $message   = $errorBody['message'] ?? $errorBody['hint'] ?? $response->body();

            return redirect()->back()->withErrors(['class_error' => 'Supabase Error: ' . $message]);

        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['class_error' => 'Connection Exception: ' . $e->getMessage()]);
        }
    }
}